@startuml
|Client|
start
|Client|
:Login successfully;
:Send request to fetch drive items;
|Server|
:Sends response with drive items;
|Client|
:Click download icon on specific item;
:Send request to download file;
|Server|
:Validate;
if (file exists) then
 ->Yes;
 if (does the user has download access) then
  ->Yes;
  :Return OK response;
 else
  ->No;
  :Return error;
 endif
else
 -> No;
 :Return error;
endif
|Client|
:Return response;
:Download file;
stop
@enduml
