@startuml
|Client|
start
|Client|
:Enter the email;
:Click reset password button;
:Send HTTP reset password request to the server;
|Server|
:Validate input;
if (Email exist in DB) then
 ->Yes;
 :Only one token with the corresponding email can exist;
 if (Reset password token already exist in DB) then
  ->Yes;
  :Revoke existing token;
 else
  ->No;
 endif
 :Generate UUID as OTP;
 :OTP should be valid for no more than 1 day;
 :Save OTP in DB with the corresponding email;
 :Send email with link to the corresponding email;
else
 -> No;
endif
:Return information that email was send;
|Client|
:Return response;
stop

|Client|
start
|Client|
:Check mailbox;
:Click the reset password link;
:Redirected to the password reset page;
:Enter new password;
:Enter new re-password;
:Send HTTP new password request to the server;
|Server|
:Validate input;
if (Input valid) then
 ->Yes;
 :Hash password;
 :Call DB for a record with email and OTP;
 if (Given OTP is in DB and is valid) then
  ->Yes;
  :Save new password hash in DB;
  :Revoke used OTP;
  :Return OK and redirect to login page;
 else
  ->No;
  :Return error;
 endif
else
 -> No;
 :Return error;
endif
|Client|
:Return response;
stop
@enduml
