@startuml Upload File
start
:Login successfully;
:Click upload item button;
:Choose the file from your PC;
if (Free space exceeded) then
 ->Yes;
 :Prompt user to free up space;
 stop
else
 ->No;
 :Prompt if file with same name exists;
 :                       Upload file 
 (replace any existing file or add as new);
 if (File uploaded successfully) then
  ->Yes;
  :Click the button for upload confirmation;
  :See your file on the webpage;
 else
  ->No;
  :Show error;
  stop
 endif
endif
stop
@enduml