@startuml
|Client|
start
|Client|
:Send request to fetch drive items;
|Server|
:Sends response with drive items;
|Client|
:Click specific item;
:Send request to fetch actual specific file;
|Server|
:Validate;
if (file exists) then
 ->Yes;
 if (does the user has view access) then
  ->Yes;
  :Return OK response;
 else
  ->No;
  :Return error;
 endif
else
 -> No;
 :Return error;
endif
|Client|
:Return response;
:Render file;
stop
@enduml
