version: '3.8'
volumes: 
  dynamodb_data:
services:
  dynamodb-local:
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal
    image: "amazon/dynamodb-local"
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal
    working_dir: /home/dynamodblocal