spring:
  data:
    dynamodb:
      entity2ddl:
        auto: create
        gsiProjectionType: ALL
        readCapacity: 10
        writeCapacity: 1
drive:
  secret: default-secret
amazon:
  dynamodb:
    endpoint: http://localhost:8000/
  aws:
    accesskey: key
    secretkey: key2

management:
  endpoints:
    web:
      exposure:
        include: "*"
