spring:
  data:
    dynamodb:
      entity2ddl:
        auto: create-only
        gsiProjectionType: ALL
        readCapacity: 10
        writeCapacity: 1
  mail:
   host: smtp.gmail.com
   port: 587
   username: pwr22gpp@gmail.com
   password: mkizhrivmnzunjck
   properties.mail.smtp.auth: true
   properties.mail.smtp.starttls.enable: true

drive:
  secret: default-secret

management:
  endpoints:
    web:
      exposure:
        include: "*"
