spring:
  data:
    dynamodb:
      entity2ddl:
        auto: create
        gsiProjectionType: ALL
        readCapacity: 10
        writeCapacity: 1
  mail:
    host: smtp.mailtrap.io
    port: 587
    username: 045163784b0e8b
    password: 4134619ffae8a7
    properties:
      mail:
        smtp:
          starttls:
            enable: true
drive:
  secret: default-secret
amazon:
  s3:
    endpoint: http://s3.localhost.localstack.cloud:4566/
  dynamodb:
    endpoint: http://localhost:8000/
  aws:
    accesskey: test
    secretkey: test

management:
  endpoints:
    web:
      exposure:
        include: "*"
