@startuml Architecture Diagram
cloud "AWS" {

    database "DB" {
        [DynamoDB]
    }

    cloud "S3" {
        [File Storage]
    }

    package "Backend" {

            package "FileManagementServices" {


            package "FileDownloadService" {
               [File Download Service]
               DownloadFile - [File Download Service]
            }

            package "FileUploadService" {
               [File Upload Service]
               UploadFile - [File Upload Service]
            }

            package "FileDeleteService" {
               [File Delete Service]
               DeleteFile - [File Delete Service]
            }

            package "GrantAccessService" {
               [Grant Access Service]

               GrantAccess - [Grant Access Service]
            }

            package "RevokeAccessService" {
               [Revoke Access Service]

               RevokeAccess - [Revoke Access Service]
            }

            package "ViewFileService" {
               [View File Service]

               ViewFile - [View File Service]
            }


            }

            package "AccountManagementServices" {
            package "AuthenticationServices" {
               [Login Service]
               Login - [Login Service]
            }

            package "UpdatePasswordService" {
               [Update Password Service]
               UpdatePassword - [Update Password Service]
            }

            package "ResetPasswordService" {
               [Reset Password Service]
               GenerateLink - [Reset Password Service]
            }

            package "RegistrationService" {
               [Registration Service]
               CreateAccount - [Registration Service]
            }



            [Grant Access Service] --> [DynamoDB]
            [Revoke Access Service] --> [DynamoDB]
            [View File Service] --> [File Storage]

            [File Download Service] --> [File Storage]
            [File Delete Service] --> [File Storage]
            [File Upload Service] --> [File Storage]


            [Login Service] --> [DynamoDB]
            [Registration Service] --> [DynamoDB]
            [Update Password Service] --> [DynamoDB]
            [Reset Password Service] --> [DynamoDB]
        }

        package "Entry Point" {

            package "Authentication" {
            [AuthenticationController]


            [AuthenticationController] --> Login

            HTTP3 - [AuthenticationController]
        }

package "AccountManagement" {
            [AccountManagementController]


            [AccountManagementController] --> CreateAccount
            [AccountManagementController] --> UpdatePassword
            [AccountManagementController] --> GenerateLink



            HTTP2 - [AccountManagementController]

        }

package "FileHandling" {

            [File Handling]

            [File Handling] --> GrantAccess
            [File Handling] --> RevokeAccess
            [File Handling] --> UploadFile
            [File Handling] --> DownloadFile
            [File Handling] --> DeleteFile
            [File Handling] --> ViewFile

            HTTP1 - [File Handling]
        }
}

    }

    package "Frontend" {
        [RegisterView]
        [LoginView]

        [FileView]
    }

    FileView --> HTTP1
    RegisterView --> HTTP2
    LoginView --> HTTP3
}
@enduml