package com.groupprogrammingproject.drive.account;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Date;
import java.util.UUID;

@DynamoDBTable(tableName = "RecoveryTokens")
public class AccountRecoveryData {
    private final Date created;
    private UUID token;
    private String id;
    private Date expired;
    private boolean used;

    public AccountRecoveryData(String id) {
        final Date today = new Date();

        this.id = id;
        this.created = today;
        this.expired = new Date(today.getTime() + (1000 * 60 * 60 * 24 * 7));
        this.used = false;
    }

    @DynamoDBHashKey(attributeName = "token")
    @DynamoDBAutoGeneratedKey
    public UUID getToken() {
        return token;
    }
    // public void setToken(UUID token) { this.token = token; }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "id")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public Date getCreated() {
        return created;
    }

    @DynamoDBAttribute
    public Date getExpired() {
        return expired;
    }

    public void setExpired(Date expired) {
        this.expired = expired;
    }

    @DynamoDBAttribute
    public boolean getUsed() {
        return used;
    }

    public void setUsed(boolean used) {
        this.used = used;
    }
}
